var messages = {
  STANDARD_HEADING: '현재 시간',
  ALARM_INPUT_HEADING: '알람 등록',
  CLOCK_MODE: '시계 모드',
  CLOCK_MODE_NORMAL: '일반',
  CLOCK_MODE_VIBRATION: '진동',
  CLOCK_MODE_NIGHT: '야간',
  ALARM_MODE: '알람 모드',
  ALARM_MODE_NORMAL: '일반',
  ALARM_MODE_EMERGENCY: '긴급',
  CONTENT: '내용',
  TIME_SETTING: '시간 설정',
  ALARM_LIST: '알람 목록',
  MODE: '모드',
  REMOVE: '삭제',
  ON_OFF: '켜기/끄기',
  ON: '알람 켜짐',
  OFF: '알람 꺼짐',
  SOUND: '소리 알람',
  VIBRATION: '진동 알람',
  MESSAGES_LIST: '알람 메세지',
  ALERT_FOT_EMPTY_DATE_TIME: '날짜와 숫자 둘 다 입력해주세요.',
  ALERT_FOT_EMPTY_CONTENT: '알람 내용을 입력해주세요.',
};

export { messages };
